=== u-learn/enablix/commons/commons-xsd-to-pojo/src/main/resources/xsd/content-mapping.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">
	
	<xs:element name="contentMapping">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="container" type="contentContainerMappingType" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required"/>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="contentContainerMappingType">
		<xs:sequence>
			<xs:element name="sourceId" type="sourceIdType"/>
			<xs:element name="parent" type="parentContainerMappingType" minOccurs="0"/>
			<xs:element name="createdBy" type="sytemUserMappingType" minOccurs="0"/>
			<xs:element name="modifiedBy" type="sytemUserMappingType" minOccurs="0"/>
			<xs:element name="contentItemMappings" type="contentItemMappingsType"/>
			<xs:element name="containerMappings" type="containerMappingsType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="qualifiedId" type="xs:string" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="sourceIdType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>	
	
	<xs:complexType name="parentContainerMappingType">
		<xs:sequence>
			<xs:element name="containerMapping" type="containerMappingType"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="containerMappingType">
		<xs:sequence>
			<xs:element name="itemMapping" type="contentItemMappingType"/>
		</xs:sequence>
		<xs:attribute name="qualifiedId" type="xs:string" use="optional"/>
		<xs:attribute name="id" type="xs:string" use="optional"/>
	</xs:complexType>
	
	<xs:complexType name="sytemUserMappingType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="attribute" type="xs:string"/>	
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	
	<xs:complexType name="contentItemMappingsType">
		<xs:sequence>
			<xs:element name="itemMapping" type="contentItemMappingType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="contentItemMappingType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="itemId" type="xs:string"/>
				<xs:attribute name="listAttribute" type="contentItemListAttrType"/>
				<xs:attribute name="default" type="xs:string"/>	
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	
	<xs:simpleType name="contentItemListAttrType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ID" />
			<xs:enumeration value="LABEL" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="containerMappingsType">
		<xs:sequence>
			<xs:element name="containerMapping" type="containerMappingType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
</xs:schema>

=== u-learn/enablix/services/enablix-app/ext-resources/content-mapping/eoriginal/salesforce-content-mapping.xml
<?xml version="1.0" encoding="utf-8"?>
<contentMapping id="sf" name="Salesforce content mapping" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/content-mapping.xsd">
	
	<container qualifiedId="opportunity">
		<sourceId>Id</sourceId>
		<createdBy attribute="profile.name">CreatedBy.Name</createdBy>
		<modifiedBy attribute="profile.name">LastModifiedBy.Name</modifiedBy>
		<contentItemMappings>
			<itemMapping itemId="title">Name</itemMapping>
			<itemMapping itemId="stage" listAttribute="LABEL">StageName</itemMapping>
			<itemMapping itemId="opportunityAccount">Account.Name</itemMapping>
		</contentItemMappings>
	</container>

</contentMapping>

=== u-learn/enablix/services/enablix-app/ext-resources/content-mapping/enablixmaster/salesforce-content-mapping.xml
<?xml version="1.0" encoding="utf-8"?>
<contentMapping id="sf" name="Salesforce content mapping" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/content-mapping.xsd">
	
	<container qualifiedId="customer.opportunity">
		<sourceId>Id</sourceId>
		<parent>
			<containerMapping qualifiedId="customer">
				<itemMapping itemId="name">Account.Name</itemMapping>
			</containerMapping>
		</parent>
		<createdBy attribute="profile.name">CreatedBy.Name</createdBy>
		<modifiedBy attribute="profile.name">LastModifiedBy.Name</modifiedBy>
		<contentItemMappings>
			<itemMapping itemId="title">Name</itemMapping>
			<itemMapping itemId="stage" listAttribute="LABEL">StageName</itemMapping>
			<itemMapping itemId="oppSolutions" listAttribute="LABEL">Solution__c</itemMapping>
			<itemMapping itemId="oppCompetitors">Competitor__c</itemMapping>
			<itemMapping itemId="oppCustomers">Account.Name</itemMapping>
		</contentItemMappings>
	</container>

</contentMapping>

=== u-learn/enablix/services/enablix-app/ext-resources/content-mapping/haystax/wordpress-content-mapping.xml
<?xml version="1.0" encoding="utf-8"?>
<contentMapping id="Wordpress-WP-Post" name="Wordpress Post content mapping" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/content-mapping.xsd">
	
	<container qualifiedId="blog">
		<sourceId>post.id</sourceId>
		<contentItemMappings>
			<itemMapping itemId="title">post.title.rendered</itemMapping>
			<itemMapping itemId="url">post.link</itemMapping>
			<itemMapping itemId="blogdate">post.date_gmt</itemMapping>
			<!-- default visibility = Everyone -->
			<itemMapping itemId="visibility" listAttribute="ID" 
						 default="597c02aa-0b62-429b-9826-a52bfccfb2f6"></itemMapping>
		</contentItemMappings>
	</container>
	
	<container qualifiedId="article">
		<sourceId>post.id</sourceId>
		<contentItemMappings>
			<itemMapping itemId="title">post.title.rendered</itemMapping>
			<itemMapping itemId="url">post.link</itemMapping>
			<!-- default visibility = Everyone -->
			<itemMapping itemId="visibility" listAttribute="ID" 
			   			 default="597c02aa-0b62-429b-9826-a52bfccfb2f6"></itemMapping>
		</contentItemMappings>
	</container>

</contentMapping>
