=== u-learn/enablix/commons/commons-xsd-to-pojo/src/main/resources/xsd/item-correlation-rule.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">
	
	<xs:element name="itemCorrelationRules">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="itemCorrelationRule" type="itemCorrelationRuleType" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="itemCorrelationRuleType">
		<xs:sequence>
			<xs:element name="triggerItem" type="triggerItemType"/>
			<xs:element name="relatedItems" type="relatedItemsType"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string"/>
		<xs:attribute name="name" type="xs:string"/>
	</xs:complexType>
	
	<xs:complexType name="triggerItemType">
		<xs:sequence>
			<xs:element name="filterCriteria" type="filterCriteriaType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="qualifiedId" type="xs:string"/>
	</xs:complexType>
	
	<xs:complexType name="filterCriteriaType">
		<xs:sequence>
			<xs:element name="filter" type="filterType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="filterType">
		<xs:sequence>
			<xs:element name="attributeId" type="xs:string"/>
			<xs:choice>
				<xs:element name="constant" type="filterConstantType"/>
				<xs:element name="parentAttribute" type="filterParentAttributeType"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="filterConstantType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	
	<xs:complexType name="filterParentAttributeType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="parentQId" type="xs:string" use="optional"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	
	<xs:complexType name="relatedItemsType">
		<xs:sequence>
			<xs:element name="relatedItem" type="relatedItemType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="relatedItemType">
		<xs:sequence>
			<xs:element name="filterCriteria" type="filterCriteriaType" minOccurs="0"/>
			<xs:element name="matchCriteria" type="matchCriteriaType" minOccurs="0"/>
			<xs:element name="recordAsRelated" type="xs:boolean" default="true"/>
			<xs:element name="tags" type="tagsType" minOccurs="0"/>
			<xs:element name="relatedItem" type="relatedItemType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="qualifiedId" type="xs:string"/>
	</xs:complexType>
	
	<xs:complexType name="matchCriteriaType">
		<xs:sequence>
			<xs:element name="match" type="matchType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="matchType">
		<xs:complexContent>
			<xs:extension base="filterType"></xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="tagsType">
		<xs:sequence>
			<xs:element name="tag" type="xs:string" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<!-- Item user correlation rules -->
	<xs:element name="itemUserCorrelationRules">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="itemUserCorrelationRule" type="itemUserCorrelationRuleType" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="itemUserCorrelationRuleType">
		<xs:sequence>
			<xs:element name="triggerItem" type="triggerItemType"/>
			<xs:element name="relatedUsers" type="relatedUsersType"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string"/>
		<xs:attribute name="name" type="xs:string"/>
	</xs:complexType>
	
	<xs:complexType name="relatedUsersType">
		<xs:sequence>
			<xs:element name="relatedUserPath" type="relatedUserPathType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="relatedUserPathType">
		<xs:sequence>
			<xs:choice>
				<xs:element name="relatedUser" type="relatedUserType"/>
				<xs:element name="pathItem" type="pathItemType"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="pathItemType">
		<xs:sequence>
			<xs:element name="filterCriteria" type="filterCriteriaType"/>
			<xs:choice>
				<xs:element name="relatedUser" type="relatedUserType"/>
				<xs:element name="pathItem" type="pathItemType"/>
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="qualifiedId" type="xs:string"/>
	</xs:complexType>
	
	<xs:complexType name="relatedUserType">
		<xs:sequence>
			<xs:element name="filterCriteria" type="filterCriteriaType"/>
			<xs:element name="tags" type="tagsType"/>
		</xs:sequence>
	</xs:complexType>
	
</xs:schema>

=== u-learn/enablix/services/enablix-app/ext-resources/item-user-corr/oraclefccm/add-update-user-corr.xml
<?xml version="1.0" encoding="utf-8"?>
<itemUserCorrelationRules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/item-correlation-rule.xsd">
	<itemUserCorrelationRule id="other-content-pipeline-report-user" name="Other Content - Pipeline Report Users">
		<triggerItem qualifiedId="content">
			<filterCriteria>
				<filter>
					<attributeId>documentType</attributeId>
					<constant>Pipeline Report</constant>
				</filter>
			</filterCriteria>
		</triggerItem>
		<relatedUsers>
			<relatedUserPath>
				<relatedUser>
					<tags>
						<tag>ALL_USERS</tag>
					</tags>
				</relatedUser>
			</relatedUserPath>
		</relatedUsers>
	</itemUserCorrelationRule>
	<itemUserCorrelationRule id="case-study-user" name="Case Study - Users">
		<triggerItem qualifiedId="caseStudy">
		</triggerItem>
		<relatedUsers>
			<relatedUserPath>
				<pathItem qualifiedId="businessRole">
					<filterCriteria>
						<filter>
							<attributeId>roleName</attributeId>
							<constant>PreSales</constant>
						</filter>
					</filterCriteria>
					<relatedUser>
						<filterCriteria>
							<filter>
								<attributeId>role</attributeId>
								<parentAttribute>identity</parentAttribute>
							</filter>
						</filterCriteria>
						<tags>
							<tag>PRE_SALES_USER</tag>
						</tags>
					</relatedUser>
				</pathItem>
			</relatedUserPath>
		</relatedUsers>
	</itemUserCorrelationRule>	
</itemUserCorrelationRules>

=== u-learn/enablix/services/enablix-app/ext-resources/item-user-corr/enablixmaster/add-update-casestudy-user-corr.xml
<?xml version="1.0" encoding="utf-8"?>
<itemUserCorrelationRules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/item-correlation-rule.xsd">
	<itemUserCorrelationRule id="case-study-opp-creator" name="Case Study - Opportunity creator">
		<triggerItem qualifiedId="caseStudy">
		</triggerItem>
		<relatedUsers>
			<relatedUserPath>
				<pathItem qualifiedId="customer.opportunity">
					<filterCriteria>
						<filter>
							<attributeId>oppSolutions</attributeId>
							<parentAttribute>solutions</parentAttribute>
						</filter>
					</filterCriteria>
					<relatedUser>
						<filterCriteria>
							<filter>
								<attributeId>email</attributeId>
								<parentAttribute>createdBy</parentAttribute>
							</filter>
						</filterCriteria>
						<tags>
							<tag>OPP_VIA_SOLN_CREATOR</tag>
						</tags>
					</relatedUser>
				</pathItem>
			</relatedUserPath>
		</relatedUsers>
	</itemUserCorrelationRule>	
</itemUserCorrelationRules>

=== u-learn/enablix/services/enablix-app/ext-resources/item-item-corr/enablixmaster/customer-correlations.xml
<?xml version="1.0" encoding="utf-8"?>
<itemCorrelationRules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/item-correlation-rule.xsd">
	<itemCorrelationRule id="cust-corr" name="Customer correlations">
		<triggerItem qualifiedId="customer">
		</triggerItem>		
		<relatedItems>
			<!-- Customer to customer opportunity -->
			<relatedItem qualifiedId="customer.opportunity">
				<filterCriteria>
					<filter>
						<attributeId>__associations.parent.recordIdentity</attributeId>
						<parentAttribute>identity</parentAttribute>
					</filter>
				</filterCriteria>
				<recordAsRelated>true</recordAsRelated>
			</relatedItem>	
		</relatedItems>
	</itemCorrelationRule>		
</itemCorrelationRules>

=== u-learn/enablix/services/enablix-app/ext-resources/item-item-corr/enablixmaster/add-update-opportunity-correlations.xml
<?xml version="1.0" encoding="utf-8"?>
<itemCorrelationRules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/item-correlation-rule.xsd">
	<itemCorrelationRule id="opp-stage-corr" name="Opportunity - Stage correlation">
		<triggerItem qualifiedId="customer.opportunity">
		</triggerItem>		
		<relatedItems>
			<!-- Priority Documents by stages -->
			<relatedItem qualifiedId="solution">
				<filterCriteria>
					<filter>
						<attributeId>identity</attributeId>
						<parentAttribute>oppSolutions</parentAttribute>
					</filter>
				</filterCriteria>
				<recordAsRelated>true</recordAsRelated>
				<tags>
					<tag>SOLN_DOC</tag>
				</tags>
				<!-- Product datasheet is correlated for qualification stage -->
				<relatedItems>				
					<relatedItem qualifiedId="product.dataSheet">
						<filterCriteria>
							<filter>
								<attributeId>__associations.parent.recordIdentity</attributeId>
								<parentAttribute>products</parentAttribute>
							</filter>
						</filterCriteria>
						<recordAsRelated>true</recordAsRelated>
						<tags>
							<tag>PRIORITY_Qualification</tag>
						</tags>
					</relatedItem>
				</relatedItems>				
			</relatedItem>
			<!-- Solution Overview is correlated for qualification stage -->				
			<relatedItem qualifiedId="solution.solOverview">
				<filterCriteria>
					<filter>
						<attributeId>__associations.parent.recordIdentity</attributeId>
						<parentAttribute>oppSolutions</parentAttribute>
					</filter>
				</filterCriteria>
				<recordAsRelated>true</recordAsRelated>
				<tags>
					<tag>PRIORITY_Qualification</tag>
					<tag>SOLN_DOC</tag>
				</tags>
			</relatedItem>	
			<!-- Discovery Questions are correlated for qualification stage -->				
			<relatedItem qualifiedId="discoveryQuestion">
				<filterCriteria>
					<filter>
						<attributeId>solutions</attributeId>
						<parentAttribute>oppSolutions</parentAttribute>
					</filter>
				</filterCriteria>
				<recordAsRelated>true</recordAsRelated>
				<tags>
					<tag>PRIORITY_Qualification</tag>
					<tag>SOLN_DOC</tag>
				</tags>
			</relatedItem>					
			<!-- Executive Summary is correlated for proposal stage -->				
			<relatedItem qualifiedId="execSummary">
				<filterCriteria>
					<filter>
						<attributeId>solutions</attributeId>
						<parentAttribute>oppSolutions</parentAttribute>
					</filter>
				</filterCriteria>
				<recordAsRelated>true</recordAsRelated>
				<tags>
					<tag>PRIORITY_Proposal</tag>
					<tag>SOLN_DOC</tag>
				</tags>
			</relatedItem>	
			<!-- Proposal is correlated for proposal stage based on solution and competitor-->				
			<relatedItem qualifiedId="proposal">
				<filterCriteria>
					<filter>
						<attributeId>solutions</attributeId>
						<parentAttribute>oppSolutions</parentAttribute>
					</filter>
					<filter>
						<attributeId>competitors</attributeId>
						<parentAttribute>oppCompetitors</parentAttribute>
					</filter>					
				</filterCriteria>
				<recordAsRelated>true</recordAsRelated>
				<tags>
					<tag>PRIORITY_Proposal</tag>
				</tags>
			</relatedItem>									
			<!-- Sales Deck is correlated for value proposition stage -->				
			<relatedItem qualifiedId="salesDeck">
				<filterCriteria>
					<filter>
						<attributeId>solutions</attributeId>
						<parentAttribute>oppSolutions</parentAttribute>
					</filter>
				</filterCriteria>
				<recordAsRelated>true</recordAsRelated>
				<tags>
					<tag>PRIORITY_Value Proposition</tag>
					<tag>SOLN_DOC</tag>
				</tags>
			</relatedItem>	
			<!-- Case Study is correlated for value proposition stage based on solution and competitor -->				
			<relatedItem qualifiedId="caseStudy">
				<filterCriteria>
					<filter>
						<attributeId>solutions</attributeId>
						<parentAttribute>oppSolutions</parentAttribute>
					</filter>
					<filter>
						<attributeId>competitors</attributeId>
						<parentAttribute>oppCompetitors</parentAttribute>
					</filter>					
				</filterCriteria>
				<recordAsRelated>true</recordAsRelated>
				<tags>
					<tag>PRIORITY_Value Proposition</tag>
					<tag>SOLN_DOC</tag>
					<tag>COMP_DOC</tag>					
				</tags>
			</relatedItem>	
			<!-- Win Loss Analysis is correlated for value proposition stage based on solution and competitor -->				
			<relatedItem qualifiedId="winloss">
				<filterCriteria>
					<filter>
						<attributeId>solutions</attributeId>
						<parentAttribute>oppSolutions</parentAttribute>
					</filter>
					<filter>
						<attributeId>competitors</attributeId>
						<parentAttribute>oppCompetitors</parentAttribute>
					</filter>					
				</filterCriteria>
				<recordAsRelated>true</recordAsRelated>
				<tags>
					<tag>PRIORITY_Value Proposition</tag>
					<tag>PRIORITY_Negotiation</tag>
					<tag>COMP_DOC</tag>					
				</tags>
			</relatedItem>		
			<!-- Solution Documents in addition to the one already tagged -->
			<!-- Blogs that are correlated to the solution -->				
			<relatedItem qualifiedId="blog">
				<filterCriteria>
					<filter>
						<attributeId>solutions</attributeId>
						<parentAttribute>oppSolutions</parentAttribute>
					</filter>
				</filterCriteria>
				<recordAsRelated>true</recordAsRelated>
				<tags>
					<tag>SOLN_DOC</tag>
				</tags>
			</relatedItem>				
			<!-- Whitepapers that are correlated to the solution -->				
			<relatedItem qualifiedId="whitepaper">
				<filterCriteria>
					<filter>
						<attributeId>solutions</attributeId>
						<parentAttribute>oppSolutions</parentAttribute>
					</filter>
				</filterCriteria>
				<recordAsRelated>true</recordAsRelated>
				<tags>
					<tag>SOLN_DOC</tag>
				</tags>
			</relatedItem>	
			<!-- Competitor documents in addition to the one already tagged -->
			<!-- Competitor link -->
			<relatedItem qualifiedId="competitor">
				<filterCriteria>
					<filter>
						<attributeId>identity</attributeId>
						<parentAttribute>oppCompetitors</parentAttribute>
					</filter>
				</filterCriteria>
				<recordAsRelated>true</recordAsRelated>
				<tags>
					<tag>COMP_DOC</tag>
				</tags>			
			</relatedItem>	
			<!-- Competitor SWOT -->								
			<relatedItem qualifiedId="competitor.compswot">
				<filterCriteria>
					<filter>
						<attributeId>__associations.parent.recordIdentity</attributeId>
						<parentAttribute>oppCompetitors</parentAttribute>
					</filter>
				</filterCriteria>
				<recordAsRelated>true</recordAsRelated>
				<tags>
					<tag>COMP_DOC</tag>
				</tags>
			</relatedItem>
			<!-- Analyst Reports based on competitor -->											
			<relatedItem qualifiedId="analyst.report">
				<filterCriteria>
					<filter>
						<attributeId>competitors</attributeId>
						<parentAttribute>oppCompetitors</parentAttribute>
					</filter>
				</filterCriteria>
				<recordAsRelated>true</recordAsRelated>
				<tags>
					<tag>COMP_DOC</tag>
				</tags>
			</relatedItem>			
			<!-- Process documents based on stages -->			
			<!-- NDA -->
			<relatedItem qualifiedId="nda">
				<recordAsRelated>true</recordAsRelated>
				<tags>
					<tag>PROCESS_Qualification</tag>
					<tag>PROCESS_Value Proposition</tag>					
				</tags>		
			</relatedItem>
			<!-- Pricing Template -->
			<relatedItem qualifiedId="pricingtemplate">
				<recordAsRelated>true</recordAsRelated>
				<tags>
					<tag>PROCESS_Negotiation</tag>
					<tag>PROCESS_Proposal</tag>					
				</tags>		
			</relatedItem>
			<!-- PPT Template -->
			<relatedItem qualifiedId="ppttemplate">
				<recordAsRelated>true</recordAsRelated>
				<tags>
					<tag>PROCESS_Value Proposition</tag>
				</tags>		
			</relatedItem>
			<!-- MSA -->
			<relatedItem qualifiedId="msa">
				<recordAsRelated>true</recordAsRelated>
				<tags>
					<tag>PROCESS_Value Proposition</tag>
					<tag>PROCESS_Negotiation</tag>										
				</tags>		
			</relatedItem>
			<!-- SOW -->
			<relatedItem qualifiedId="sow">
				<recordAsRelated>true</recordAsRelated>
				<tags>
					<tag>PROCESS_Negotiation</tag>										
				</tags>		
			</relatedItem>
		</relatedItems>
	</itemCorrelationRule>		
</itemCorrelationRules>

=== u-learn/enablix/services/enablix-app/ext-resources/item-item-corr/enablixmaster/competitor-correlations.xml
<?xml version="1.0" encoding="utf-8"?>
<itemCorrelationRules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/item-correlation-rule.xsd">
	<itemCorrelationRule id="competitor-corr" name="Competitor correlations">
		<triggerItem qualifiedId="competitor">
		</triggerItem>		
		<relatedItems>
			<!-- Customer to customer opportunity -->
			<relatedItem qualifiedId="customer.opportunity">
				<filterCriteria>
					<filter>
						<attributeId>oppCompetitors</attributeId>
						<parentAttribute>identity</parentAttribute>
					</filter>
				</filterCriteria>
				<recordAsRelated>true</recordAsRelated>
			</relatedItem>	
		</relatedItems>
	</itemCorrelationRule>		
</itemCorrelationRules>

=== u-learn/enablix/services/enablix-app/ext-resources/item-item-corr/enablixmaster/add-update-item-corr.xml
<?xml version="1.0" encoding="utf-8"?>
<itemCorrelationRules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/item-correlation-rule.xsd">
	<itemCorrelationRule id="opportunity-whitepaper-corr" name="Opportunity-Whitepaper via Solution">
		<triggerItem qualifiedId="customer.opportunity">
		</triggerItem>
		<relatedItems>
			<relatedItem qualifiedId="whitepaper">
				<filterCriteria>
					<filter>
						<attributeId>solutions</attributeId>
						<parentAttribute>oppSolutions</parentAttribute>
					</filter>
				</filterCriteria>
				<recordAsRelated>true</recordAsRelated>
				<tags>
					<tag>LINK_VIA_SOLN</tag>
				</tags>
			</relatedItem>
		</relatedItems>
	</itemCorrelationRule>
</itemCorrelationRules>

=== u-learn/enablix/services/enablix-app/ext-resources/item-item-corr/enablixmaster/item-correlations.xml
<?xml version="1.0" encoding="utf-8"?>
<itemCorrelationRules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/item-correlation-rule.xsd">
	<itemCorrelationRule id="rule1" name="Solution-Product via Impl Guide">
		<triggerItem qualifiedId="solution">
		</triggerItem>
		<relatedItems>
			<relatedItem qualifiedId="product">
				<filterCriteria>
					<filter>
						<attributeId>identity</attributeId>
						<parentAttribute>products</parentAttribute>
					</filter>
				</filterCriteria>
				<matchCriteria>
					<match>
						<attributeId>name</attributeId>
						<parentAttribute>shortName</parentAttribute>
					</match>
				</matchCriteria>
				<recordAsRelated>true</recordAsRelated>
				<tags>
					<tag>DIRECT_LINK</tag>
				</tags>
			</relatedItem>
		</relatedItems>
	</itemCorrelationRule>
</itemCorrelationRules>

=== u-learn/enablix/services/enablix-app/ext-resources/item-item-corr/test/item-correlations.xml
<?xml version="1.0" encoding="utf-8"?>
<itemCorrelationRules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/item-correlation-rule.xsd">
	<itemCorrelationRule id="rule1" name="Solution-Product via Impl Guide">
		<triggerItem qualifiedId="solution">
			<filterCriteria>
				<filter>
					<attributeId>regions</attributeId>
					<constant>NAM</constant>
				</filter>
			</filterCriteria>
		</triggerItem>
		<relatedItems>
			<relatedItem qualifiedId="solution.solImplGuides">
				<filterCriteria>
					<filter>
						<attributeId>solutions</attributeId>
						<parentAttribute>identity</parentAttribute>
					</filter>
					<filter>
						<attributeId>access</attributeId>
						<constant>PRIVATE</constant>
					</filter>
				</filterCriteria>
				<matchCriteria>
					<match>
						<attributeId>summary</attributeId>
						<parentAttribute>name</parentAttribute>
					</match>
				</matchCriteria>
				<recordAsRelated>false</recordAsRelated>
				<tags>
					<tag>LEVEL1_DOC</tag>
				</tags>
				<!-- Second level -->
				<relatedItems>
					<relatedItem qualifiedId="product">
						<filterCriteria>
							<filter>
								<attributeId>identity</attributeId>
								<parentAttribute>products</parentAttribute>
							</filter>
						</filterCriteria>
						<recordAsRelated>true</recordAsRelated>
						<tags>
							<tag>PRIMARY_PRODUCT</tag>
						</tags>	
					</relatedItem>
				</relatedItems>
			</relatedItem>
		</relatedItems>
	</itemCorrelationRule>
</itemCorrelationRules>
