=== u-learn/enablix/commons/commons-xsd-to-pojo/src/main/resources/xsd/item-correlation-rule.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">
	
	<xs:element name="itemCorrelationRules">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="itemCorrelationRule" type="itemCorrelationRuleType" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="itemCorrelationRuleType">
		<xs:sequence>
			<xs:element name="triggerItem" type="triggerItemType"/>
			<xs:element name="relatedItems" type="relatedItemsType"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string"/>
		<xs:attribute name="name" type="xs:string"/>
	</xs:complexType>
	
	<xs:complexType name="triggerItemType">
		<xs:sequence>
			<xs:element name="filterCriteria" type="filterCriteriaType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="qualifiedId" type="xs:string"/>
	</xs:complexType>
	
	<xs:complexType name="filterCriteriaType">
		<xs:sequence>
			<xs:element name="filter" type="filterType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="filterType">
		<xs:sequence>
			<xs:element name="attributeId" type="xs:string"/>
			<xs:choice>
				<xs:element name="constant" type="filterConstantType"/>
				<xs:element name="parentAttribute" type="filterParentAttributeType"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="filterConstantType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	
	<xs:complexType name="filterParentAttributeType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="parentQId" type="xs:string" use="optional"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	
	<xs:complexType name="relatedItemsType">
		<xs:sequence>
			<xs:element name="relatedItem" type="relatedItemType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="relatedItemType">
		<xs:sequence>
			<xs:element name="filterCriteria" type="filterCriteriaType" minOccurs="0"/>
			<xs:element name="matchCriteria" type="matchCriteriaType" minOccurs="0"/>
			<xs:element name="recordAsRelated" type="xs:boolean" default="true"/>
			<xs:element name="tags" type="tagsType" minOccurs="0"/>
			<xs:element name="relatedItem" type="relatedItemType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="qualifiedId" type="xs:string"/>
	</xs:complexType>
	
	<xs:complexType name="matchCriteriaType">
		<xs:sequence>
			<xs:element name="match" type="matchType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="matchType">
		<xs:complexContent>
			<xs:extension base="filterType"></xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="tagsType">
		<xs:sequence>
			<xs:element name="tag" type="xs:string" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<!-- Item user correlation rules -->
	<xs:element name="itemUserCorrelationRules">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="itemUserCorrelationRule" type="itemUserCorrelationRuleType" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="itemUserCorrelationRuleType">
		<xs:sequence>
			<xs:element name="triggerItem" type="triggerItemType"/>
			<xs:element name="relatedUsers" type="relatedUsersType"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string"/>
		<xs:attribute name="name" type="xs:string"/>
	</xs:complexType>
	
	<xs:complexType name="relatedUsersType">
		<xs:sequence>
			<xs:element name="relatedUserPath" type="relatedUserPathType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="relatedUserPathType">
		<xs:sequence>
			<xs:choice>
				<xs:element name="relatedUser" type="relatedUserType"/>
				<xs:element name="pathItem" type="pathItemType"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="pathItemType">
		<xs:sequence>
			<xs:element name="filterCriteria" type="filterCriteriaType"/>
			<xs:choice>
				<xs:element name="relatedUser" type="relatedUserType"/>
				<xs:element name="pathItem" type="pathItemType"/>
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="qualifiedId" type="xs:string"/>
	</xs:complexType>
	
	<xs:complexType name="relatedUserType">
		<xs:sequence>
			<xs:element name="filterCriteria" type="filterCriteriaType"/>
			<xs:element name="tags" type="tagsType"/>
		</xs:sequence>
	</xs:complexType>
	
</xs:schema>

=== u-learn/enablix/services/enablix-app/ext-resources/item-item-corr/enablixmaster/add-update-item-correlations.xml
<?xml version="1.0" encoding="utf-8"?>
<itemCorrelationRules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/item-correlation-rule.xsd">
	<itemCorrelationRule id="rule1" name="Whitepaper Opportunity Correlation">
		<triggerItem qualifiedId="whitepaper">
		</triggerItem>
		<relatedItems>
			<relatedItem qualifiedId="customer.opportunity">
				<filterCriteria>
					<filter>
						<attributeId>oppProducts</attributeId>
						<parentAttribute>products</parentAttribute>
					</filter>
				</filterCriteria>
				<recordAsRelated>true</recordAsRelated>
				<tags>
					<tag>OPP_VIA_PROD</tag>
				</tags>
			</relatedItem>
		</relatedItems>
	</itemCorrelationRule>
	<itemCorrelationRule id="rule2" name="Casestudy Opportunity Correlation">
		<triggerItem qualifiedId="caseStudy">
		</triggerItem>
		<relatedItems>
			<relatedItem qualifiedId="customer.opportunity">
				<filterCriteria>
					<filter>
						<attributeId>oppProducts</attributeId>
						<parentAttribute>products</parentAttribute>
					</filter>
				</filterCriteria>
				<recordAsRelated>true</recordAsRelated>
				<tags>
					<tag>OPP_VIA_PROD</tag>
				</tags>
				<relatedItems>
					<relatedItem qualifiedId="competitor">
						<filterCriteria>
							<filter>
								<attributeId>identity</attributeId>
								<parentAttribute>oppCompetitors</parentAttribute>
							</filter>
						</filterCriteria>
						<recordAsRelated>true</recordAsRelated>
						<tags>
							<tag>COMP_VIA_OPP</tag>
						</tags>
					</relatedItem>
				</relatedItems>
			</relatedItem>
		</relatedItems>
	</itemCorrelationRule>	
</itemCorrelationRules>

=== u-learn/enablix/services/enablix-app/ext-resources/item-user-corr/enablixmaster/add-update-salesplay-user-corr.xml
<?xml version="1.0" encoding="utf-8"?>
<itemUserCorrelationRules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/item-correlation-rule.xsd">
	<itemUserCorrelationRule id="sales-play-user" name="Sales Play - Users">
		<triggerItem qualifiedId="salesPlay">
		</triggerItem>
		<relatedUsers>
			<relatedUserPath>
				<pathItem qualifiedId="businessRole">
					<filterCriteria>
						<filter>
							<attributeId>roleName</attributeId>
							<constant>Sales</constant>
						</filter>
					</filterCriteria>
					<relatedUser>
						<filterCriteria>
							<filter>
								<attributeId>role</attributeId>
								<parentAttribute>identity</parentAttribute>
							</filter>
						</filterCriteria>
						<tags>
							<tag>SALES_REPS</tag>
						</tags>
					</relatedUser>
				</pathItem>
			</relatedUserPath>
		</relatedUsers>
	</itemUserCorrelationRule>	
</itemUserCorrelationRules>

=== u-learn/enablix/services/enablix-app/ext-resources/item-user-corr/enablixmaster/add-update-casestudy-whitepaper-user-corr.xml
<?xml version="1.0" encoding="utf-8"?>
<itemUserCorrelationRules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/item-correlation-rule.xsd">
	<itemUserCorrelationRule id="white-paper-user" name="Whitepaper Opportunity User">
		<triggerItem qualifiedId="whitepaper">
		</triggerItem>
		<relatedUsers>
			<relatedUserPath>
				<pathItem qualifiedId="customer.opportunity">
					<filterCriteria>
						<filter>
							<attributeId>oppSolutions</attributeId>
							<parentAttribute>solutions</parentAttribute>
						</filter>
					</filterCriteria>
					<relatedUser>
						<filterCriteria>
							<filter>
								<attributeId>identity</attributeId>
								<parentAttribute>oppSalesMember</parentAttribute>
							</filter>
						</filterCriteria>
						<tags>
							<tag>OPP_SALES_REP</tag>
						</tags>
					</relatedUser>
				</pathItem>			
			</relatedUserPath>
		</relatedUsers>
	</itemUserCorrelationRule>
	<itemUserCorrelationRule id="case-study-user" name="Case Study - Users">
		<triggerItem qualifiedId="caseStudy">
		</triggerItem>
		<relatedUsers>
			<relatedUserPath>
				<pathItem qualifiedId="customer.opportunity">
					<filterCriteria>
						<filter>
							<attributeId>oppSolutions</attributeId>
							<parentAttribute>solutions</parentAttribute>
						</filter>
					</filterCriteria>
					<relatedUser>
						<filterCriteria>
							<filter>
								<attributeId>identity</attributeId>
								<parentAttribute>oppSalesMember</parentAttribute>
							</filter>
						</filterCriteria>
						<tags>
							<tag>OPP_SALES_REP</tag>
						</tags>
					</relatedUser>
				</pathItem>
			</relatedUserPath>
		</relatedUsers>
	</itemUserCorrelationRule>	
</itemUserCorrelationRules>

=== u-learn/enablix/services/enablix-app/ext-resources/item-item-corr/enablixmaster/add-update-salesplay-correlations.xml
<?xml version="1.0" encoding="utf-8"?>
<itemCorrelationRules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/item-correlation-rule.xsd">
	<itemCorrelationRule id="rule11" name="Product Correlation">
		<triggerItem qualifiedId="salesPlay">
		</triggerItem>
		<relatedItems>
			<relatedItem qualifiedId="product">
				<filterCriteria>
					<filter>
						<attributeId>identity</attributeId>
						<parentAttribute>products</parentAttribute>
					</filter>
				</filterCriteria>
				<recordAsRelated>true</recordAsRelated>
				<tags>
					<tag>LINKED_PROD</tag>
				</tags>
			</relatedItem>
		</relatedItems>
	</itemCorrelationRule>
	<itemCorrelationRule id="rule12" name="Solution Correlation">
		<triggerItem qualifiedId="salesPlay">
		</triggerItem>
		<relatedItems>
			<relatedItem qualifiedId="solution">
				<filterCriteria>
					<filter>
						<attributeId>identity</attributeId>
						<parentAttribute>solutions</parentAttribute>
					</filter>
				</filterCriteria>
				<recordAsRelated>true</recordAsRelated>
				<tags>
					<tag>LINKED_SOL</tag>
				</tags>
			</relatedItem>
		</relatedItems>
	</itemCorrelationRule>	
	<itemCorrelationRule id="rule13" name="Competitor Correlation">
		<triggerItem qualifiedId="salesPlay">
		</triggerItem>
		<relatedItems>
			<relatedItem qualifiedId="competitor">
				<filterCriteria>
					<filter>
						<attributeId>identity</attributeId>
						<parentAttribute>competitors</parentAttribute>
					</filter>
				</filterCriteria>
				<recordAsRelated>true</recordAsRelated>
				<tags>
					<tag>LINKED_COMP</tag>
				</tags>
			</relatedItem>
		</relatedItems>
	</itemCorrelationRule>	
	<itemCorrelationRule id="rule14" name="Product Introduction Correlation">
		<triggerItem qualifiedId="salesPlay">
		</triggerItem>
		<relatedItems>
			<relatedItem qualifiedId="product">
				<filterCriteria>
					<filter>
						<attributeId>shortName</attributeId>
						<constant>miRevenue</constant>
					</filter>
				</filterCriteria>
				<recordAsRelated>true</recordAsRelated>
				<tags>
					<tag>INTRO_PROD</tag>
				</tags>
				<relatedItems>
					<relatedItem qualifiedId="battlecard">
						<filterCriteria>
							<filter>
								<attributeId>products</attributeId>
								<parentAttribute>identity</parentAttribute>
							</filter>
						</filterCriteria>
						<recordAsRelated>true</recordAsRelated>
						<tags>
							<tag>PROD_BATTLECARD</tag>
						</tags>
					</relatedItem>				
					<relatedItem qualifiedId="salesDeck">
						<filterCriteria>
							<filter>
								<attributeId>products</attributeId>
								<parentAttribute>identity</parentAttribute>
							</filter>
						</filterCriteria>
						<recordAsRelated>true</recordAsRelated>
						<tags>
							<tag>PROD_SALES_DECK</tag>
						</tags>
					</relatedItem>								
					<relatedItem qualifiedId="whitepaper">
						<filterCriteria>
							<filter>
								<attributeId>products</attributeId>
								<parentAttribute>identity</parentAttribute>
							</filter>
						</filterCriteria>
						<recordAsRelated>true</recordAsRelated>
						<tags>
							<tag>PROD_WP</tag>
						</tags>
					</relatedItem>	
					<relatedItem qualifiedId="caseStudy">
						<filterCriteria>
							<filter>
								<attributeId>products</attributeId>
								<parentAttribute>identity</parentAttribute>
							</filter>
						</filterCriteria>
						<recordAsRelated>true</recordAsRelated>
						<tags>
							<tag>PROD_CS</tag>
						</tags>
					</relatedItem>
				</relatedItems>								
			</relatedItem>
		</relatedItems>
	</itemCorrelationRule>		
</itemCorrelationRules>

=== u-learn/enablix/services/enablix-app/ext-resources/item-user-corr/enablixmaster/item-user-correlations.xml
<?xml version="1.0" encoding="utf-8"?>
<itemUserCorrelationRules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/item-correlation-rule.xsd">
	<itemUserCorrelationRule id="itemUserRule1" name="Solution sheet - Matching user region">
		<triggerItem qualifiedId="solution.solutionSheet">
		</triggerItem>
		<relatedUsers>
			<relatedUserPath>
				<pathItem qualifiedId="businessRole">
					<filterCriteria>
						<filter>
							<attributeId>role</attributeId>
							<constant>Sales</constant>
						</filter>
					</filterCriteria>
					<relatedUser>
						<filterCriteria>
							<filter>
								<attributeId>userSolArea</attributeId>
								<parentAttribute parentQId="solution">solArea</parentAttribute>
							</filter>
							<filter>
								<attributeId>role</attributeId>
								<parentAttribute>identity</parentAttribute>
							</filter>
						</filterCriteria>
						<tags>
							<tag>SALES_PERSON</tag>
						</tags>
					</relatedUser>
				</pathItem>
			</relatedUserPath>
		</relatedUsers>
	</itemUserCorrelationRule>
</itemUserCorrelationRules>

=== u-learn/enablix/services/enablix-app/ext-resources/item-user-corr/oraclefccm/item-user-correlations.xml
<?xml version="1.0" encoding="utf-8"?>
<itemUserCorrelationRules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/item-correlation-rule.xsd">
	<itemUserCorrelationRule id="caseStudyUserRule" name="Case Study - User Notification">
		<triggerItem qualifiedId="caseStudy">
		</triggerItem>
		<relatedUsers>
			<relatedUserPath>
				<pathItem qualifiedId="businessRole">
					<filterCriteria>
						<filter>
							<attributeId>role</attributeId>
							<constant>PreSales</constant>
						</filter>
					</filterCriteria>
					<relatedUser>
						<filterCriteria>
							<filter>
								<attributeId>role</attributeId>
								<parentAttribute>identity</parentAttribute>
							</filter>
						</filterCriteria>
						<tags>
							<tag>PRE_SALES_USER</tag>
						</tags>
					</relatedUser>
				</pathItem>
			</relatedUserPath>
		</relatedUsers>
	</itemUserCorrelationRule>
</itemUserCorrelationRules>

=== u-learn/enablix/services/enablix-app/ext-resources/item-item-corr/enablixmaster/add-update-casestudy-correlations.xml
<?xml version="1.0" encoding="utf-8"?>
<itemCorrelationRules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/item-correlation-rule.xsd">
	
	<itemCorrelationRule id="casestudy-opp-via-soln" name="Casestudy to Opportunity Via Solution">
		<triggerItem qualifiedId="caseStudy">
		</triggerItem>
		<relatedItems>
			<relatedItem qualifiedId="customer.opportunity">
				<filterCriteria>
					<filter>
						<attributeId>oppSolutions</attributeId>
						<parentAttribute>solutions</parentAttribute>
					</filter>
				</filterCriteria>
				<recordAsRelated>true</recordAsRelated>
				<tags>
					<tag>OPP_VIA_SOLN</tag>
				</tags>
			</relatedItem>
		</relatedItems>
	</itemCorrelationRule>	
	
</itemCorrelationRules>

=== u-learn/enablix/services/enablix-app/ext-resources/item-user-corr/oraclefccm/other-content-user-corr.xml
<?xml version="1.0" encoding="utf-8"?>
<itemUserCorrelationRules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/item-correlation-rule.xsd">
	<itemUserCorrelationRule id="other-content-pipeline-report-user" name="Other Content - Pipeline Report Users">
		<triggerItem qualifiedId="content">
			<filterCriteria>
				<filter>
					<attributeId>documentType</attributeId>
					<constant>Pipeline Report</constant>
				</filter>
			</filterCriteria>
		</triggerItem>
		<relatedUsers>
			<relatedUserPath>
				<relatedUser>
					<tags>
						<tag>ALL_USERS</tag>
					</tags>
				</relatedUser>
			</relatedUserPath>
		</relatedUsers>
	</itemUserCorrelationRule>
</itemUserCorrelationRules>
