=== u-learn/enablix/commons/commons-xsd-to-pojo/src/main/resources/xsd/trigger-lifecycle.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">
	
	
	<xs:element name="triggersDef">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="contentTriggerDef" type="contentTriggerDefType" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="contentTriggerDefType">
		<xs:sequence>
			<xs:element name="candidateContainers" type="candidateContainersType" maxOccurs="unbounded"/>
			<xs:element name="lifecycle" type="lifecycleType" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="type" type="triggerTypeEnum" use="required"/>
		<xs:attribute name="id" type="xs:string" use="required"/>
	</xs:complexType>
	
	<xs:simpleType name="triggerTypeEnum">
		<xs:restriction base="xs:string">
			<xs:enumeration value="CONTENT_ADD" />
			<xs:enumeration value="CONTENT_UPDATE" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="execTimeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="NOW" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="candidateContainersType">
		<xs:sequence>
			<xs:element name="containerQId" type="xs:string" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="lifecycleType">
		<xs:sequence>
			<xs:element name="checkpoint" type="checkpointType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="checkpointType">
		<xs:sequence>
			<xs:element name="executionTime" type="executionTimeType"/>
			<xs:element name="actions" type="actionsType"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="executionTimeType">
		<xs:attribute name="type" type="execTimeType"/>
	</xs:complexType>
	
	<xs:complexType name="actionsType">
		<xs:sequence>
			<xs:element name="correlation" type="correlationActionType"/>
			<xs:element name="email" type="emailActionType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="actionType">
		<xs:attribute name="execOrder" type="xs:integer" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="correlationActionType">
		<xs:complexContent>
			<xs:extension base="actionType">
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="emailActionType">
		<xs:complexContent>
			<xs:extension base="actionType">
				<xs:sequence>
					<xs:element name="emailTemplate" type="emailTemplateType"/>
					<xs:element name="emailContent" type="emailContentType"/>
					<xs:element name="recipient" type="emailRecipientType"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="emailTemplateType">
		<xs:sequence>
			<xs:element name="subject" type="templateType"/>
			<xs:element name="body" type="templateType"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="templateType">
		<xs:attribute name="templateName" type="xs:string" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="emailContentType">
		<xs:all>
			<xs:element name="triggerEntity" type="emailContentTriggerEntityType" minOccurs="0"/>
			<xs:element name="correlatedEntities" type="correlatedEntitiesType" minOccurs="0"/>
		</xs:all>
	</xs:complexType>
	
	<xs:complexType name="baseEmailContentType">
		<xs:attribute name="name" type="xs:string"/>
	</xs:complexType>
	
	<xs:complexType name="emailContentTriggerEntityType">
		<xs:complexContent>
			<xs:extension base="baseEmailContentType">
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="correlatedEntitiesType">
		<xs:complexContent>
			<xs:extension base="baseEmailContentType">
				<xs:sequence>
					<xs:element name="entity" type="entityContentType" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="entityContentType">
		<xs:sequence>
			<xs:element name="filterTags" type="filterTagsType"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="filterTagsType">
		<xs:sequence>
			<xs:element name="tag" type="xs:string" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="emailRecipientType">
		<xs:sequence>
			<xs:element name="correlatedUsers" type="emailCorrelatedUsersType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="allUsers" type="emailAllUsersType"  minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="baseEmailRecipientType">
		<xs:attribute name="name" type="xs:string"/>
	</xs:complexType>
	
	<xs:complexType name="emailAllUsersType">
		<xs:complexContent>
			<xs:extension base="baseEmailRecipientType"/>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="emailCorrelatedUsersType">
		<xs:complexContent>
			<xs:extension base="baseEmailRecipientType">
				<xs:sequence>
					<xs:element name="users" type="emailUsersType" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="emailUsersType">
		<xs:sequence>
			<xs:element name="filterTags" type="filterTagsType"/>
		</xs:sequence>
	</xs:complexType>
	
</xs:schema>

=== u-learn/enablix/services/enablix-app/ext-resources/trigger/oraclefccm/other-content-triggers.xml
<?xml version="1.0" encoding="utf-8"?>
<triggersDef xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/trigger-lifecycle.xsd">
	<contentTriggerDef id="other-content-add-trigger" type="CONTENT_ADD">
		<candidateContainers>
			<containerQId>content</containerQId>
		</candidateContainers>
		<lifecycle>
			<checkpoint>
				<executionTime type="NOW"/>
				<actions>
					<correlation execOrder="1"/>
					<email execOrder="2">
						<emailTemplate>
							<subject templateName="addContent_subject.vm"/>
							<body templateName="addContent_body.vm"/>
						</emailTemplate>
						<emailContent>
							<triggerEntity/>
						</emailContent>
						<recipient>
							<correlatedUsers>
								<users>
									<filterTags>
										<tag>ALL_USERS</tag>
									</filterTags>
								</users>
							</correlatedUsers>
						</recipient>
					</email>
				</actions>
			</checkpoint>	
		</lifecycle>
	</contentTriggerDef>
	<contentTriggerDef id="other-content-update-trigger" type="CONTENT_UPDATE">
		<candidateContainers>
			<containerQId>content</containerQId>
		</candidateContainers>
		<lifecycle>
			<checkpoint>
				<executionTime type="LATER">
					<after timeUnit="MIN" timeValue="2"/>
				</executionTime>
				<actions>
					<correlation execOrder="1"/>
					<email execOrder="2">
						<emailTemplate>
							<subject templateName="addContent_subject.vm"/>
							<body templateName="addContent_body.vm"/>
						</emailTemplate>
						<emailContent>
							<triggerEntity/>
						</emailContent>
						<recipient>
							<correlatedUsers>
								<users>
									<filterTags>
										<tag>ALL_USERS</tag>
									</filterTags>
								</users>
							</correlatedUsers>
						</recipient>
					</email>
				</actions>
			</checkpoint>	
		</lifecycle>
	</contentTriggerDef>
</triggersDef>

=== u-learn/enablix/services/enablix-app/ext-resources/trigger/oraclefccm/system-triggers.xml
<?xml version="1.0" encoding="utf-8"?>
<triggersDef xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/trigger-lifecycle.xsd">
	<contentTriggerDef id="casestudy-add-trigger" type="CONTENT_ADD">
		<candidateContainers>
			<containerQId>caseStudy</containerQId>
		</candidateContainers>
		<lifecycle>
			<checkpoint>
				<executionTime type="NOW"/>
				<actions>
					<correlation execOrder="1"/>
					<email execOrder="2">
						<emailTemplate>
							<subject templateName="addContent_subject.vm"/>
							<body templateName="addContent_body.vm"/>
						</emailTemplate>
						<emailContent>
							<triggerEntity/>
						</emailContent>
						<recipient>
							<correlatedUsers>
								<users>
									<filterTags>
										<tag>PRE_SALES_USER</tag>
									</filterTags>
								</users>
							</correlatedUsers>
						</recipient>
					</email>
				</actions>
			</checkpoint>	
		</lifecycle>
	</contentTriggerDef>
	<contentTriggerDef id="casestudy-update-trigger" type="CONTENT_UPDATE">
		<candidateContainers>
			<containerQId>caseStudy</containerQId>
		</candidateContainers>
		<lifecycle>
			<checkpoint>
				<executionTime type="NOW"/>
				<actions>
					<correlation execOrder="1"/>
					<email execOrder="2">
						<emailTemplate>
							<subject templateName="addContent_subject.vm"/>
							<body templateName="addContent_body.vm"/>
						</emailTemplate>
						<emailContent>
							<triggerEntity/>
						</emailContent>
						<recipient>
							<correlatedUsers>
								<users>
									<filterTags>
										<tag>PRE_SALES_USER</tag>
									</filterTags>
								</users>
							</correlatedUsers>
						</recipient>
					</email>
				</actions>
			</checkpoint>	
		</lifecycle>
	</contentTriggerDef>
</triggersDef>

=== u-learn/enablix/services/enablix-app/ext-resources/trigger/enablixmaster/system-triggers.xml
<?xml version="1.0" encoding="utf-8"?>
<triggersDef xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/trigger-lifecycle.xsd">
	<contentTriggerDef id="solution-container-content-add-trigger" type="CONTENT_UPDATE">
		<candidateContainers>
			<containerQId>solution</containerQId>
			<containerQId>solution.solutionSheet</containerQId>
			<containerQId>product</containerQId>
		</candidateContainers>
		<lifecycle>
			<checkpoint>
				<executionTime type="NOW"/>
				<actions>
					<correlation execOrder="1"/>
					<email execOrder="2">
						<emailTemplate>
							<subject templateName="addContent_subject.vm"/>
							<body templateName="addContent_body.vm"/>
						</emailTemplate>
						<emailContent>
							<triggerEntity/>
						</emailContent>
						<recipient>
							<correlatedUsers>
								<users>
									<filterTags>
										<tag>SALES_PERSON</tag>
									</filterTags>
								</users>
								<users>
									<filterTags>
										<tag>#CONTENT_CREATOR#</tag>
									</filterTags>
								</users>
							</correlatedUsers>
						</recipient>
					</email>
				</actions>
			</checkpoint>	
		</lifecycle>
	</contentTriggerDef>
</triggersDef>

=== u-learn/enablix/services/enablix-app/ext-resources/trigger/simplecrm/add-update-triggers.xml
<?xml version="1.0" encoding="utf-8"?>
<triggersDef xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/trigger-lifecycle.xsd">
	<contentTriggerDef id="add-featuresheet-trigger" type="CONTENT_ADD">
		<candidateContainers>
			<containerQId>featureSheet</containerQId>
		</candidateContainers>
		<lifecycle>
			<checkpoint>
				<executionTime type="NOW"/>
				<actions>
					<email execOrder="1">
						<emailTemplate>
							<subject templateName="addContent_subject.vm"/>
							<body templateName="addContent_body.vm"/>
						</emailTemplate>
						<emailContent>
							<triggerEntity/>
						</emailContent>
						<recipient>
							<allUsers/>
						</recipient>
					</email>
				</actions>
			</checkpoint>	
		</lifecycle>
	</contentTriggerDef>
	<contentTriggerDef id="update-featuresheet-trigger" type="CONTENT_UPDATE">
		<candidateContainers>
			<containerQId>featureSheet</containerQId>
		</candidateContainers>
		<lifecycle>
			<checkpoint>
				<executionTime type="NOW"/>
				<actions>
					<email execOrder="1">
						<emailTemplate>
							<subject templateName="addContent_subject.vm"/>
							<body templateName="addContent_body.vm"/>
						</emailTemplate>
						<emailContent>
							<triggerEntity/>
						</emailContent>
						<recipient>
							<allUsers/>
						</recipient>
					</email>
				</actions>
			</checkpoint>	
		</lifecycle>
	</contentTriggerDef>
	<contentTriggerDef id="importantslide-add-trigger" type="CONTENT_ADD">
		<candidateContainers>
			<containerQId>importantslides</containerQId>
		</candidateContainers>
		<lifecycle>
			<checkpoint>
				<executionTime type="NOW"/>
				<actions>
					<email execOrder="2">
						<emailTemplate>
							<subject templateName="addContent_subject.vm"/>
							<body templateName="addContent_body.vm"/>
						</emailTemplate>
						<emailContent>
							<triggerEntity/>
						</emailContent>
						<recipient>
							<allUsers/>
						</recipient>
					</email>
				</actions>
			</checkpoint>	
		</lifecycle>
	</contentTriggerDef>
	<contentTriggerDef id="importantslide-update-trigger" type="CONTENT_UPDATE">
		<candidateContainers>
			<containerQId>importantslides</containerQId>
		</candidateContainers>
		<lifecycle>
			<checkpoint>
				<executionTime type="NOW"/>
				<actions>
					<email execOrder="2">
						<emailTemplate>
							<subject templateName="addContent_subject.vm"/>
							<body templateName="addContent_body.vm"/>
						</emailTemplate>
						<emailContent>
							<triggerEntity/>
						</emailContent>
						<recipient>
							<allUsers/>
						</recipient>
					</email>
				</actions>
			</checkpoint>	
		</lifecycle>
	</contentTriggerDef>	
</triggersDef>

=== u-learn/enablix/services/enablix-app/ext-resources/trigger/enablixmaster/add-update-casestudy-whitepaper-triggers.xml
<?xml version="1.0" encoding="utf-8"?>
<triggersDef xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/trigger-lifecycle.xsd">
	<contentTriggerDef id="add-whitepaper-trigger" type="CONTENT_ADD">
		<candidateContainers>
			<containerQId>whitepaper</containerQId>
		</candidateContainers>
		<lifecycle>
			<checkpoint>
				<executionTime type="NOW"/>
				<actions>
					<correlation execOrder="1"/>
					<email execOrder="2">
						<emailTemplate>
							<subject templateName="addContentOpp_subject.vm"/>
							<body templateName="addWhitepaperOpp_body.vm"/>
						</emailTemplate>
						<emailContent>
							<triggerEntity/>
							<correlatedEntities>
								<entity>
									<contentTypes>
										<containerQId>customer.opportunity</containerQId>
									</contentTypes>
									<filterTags>
										<tag>OPP_VIA_PROD</tag>
									</filterTags>
								</entity>
							</correlatedEntities>			
						</emailContent>
						<recipient>
							<correlatedUsers>
								<users>
									<filterTags>
										<tag>OPP_SALES_REP</tag>
									</filterTags>
								</users>
							</correlatedUsers>
						</recipient>
					</email>
				</actions>
			</checkpoint>
		</lifecycle>
	</contentTriggerDef>
	<contentTriggerDef id="update-whitepaper-trigger" type="CONTENT_UPDATE">
		<candidateContainers>
			<containerQId>whitepaper</containerQId>
		</candidateContainers>
		<lifecycle>
			<checkpoint>
				<executionTime type="NOW"/>
				<actions>
					<correlation execOrder="1"/>
					<email execOrder="2">
						<emailTemplate>
							<subject templateName="addContentOpp_subject.vm"/>
							<body templateName="addWhitepaperOpp_body.vm"/>
						</emailTemplate>
						<emailContent>
							<triggerEntity/>
							<correlatedEntities>
								<entity>
									<contentTypes>
										<containerQId>customer.opportunity</containerQId>
									</contentTypes>
									<filterTags>
										<tag>OPP_VIA_PROD</tag>
									</filterTags>
								</entity>
							</correlatedEntities>			
						</emailContent>
						<recipient>
							<correlatedUsers>
								<users>
									<filterTags>
										<tag>OPP_SALES_REP</tag>
									</filterTags>
								</users>
							</correlatedUsers>
						</recipient>
					</email>
				</actions>
			</checkpoint>	
		</lifecycle>
	</contentTriggerDef>
	<contentTriggerDef id="case-study-add-trigger" type="CONTENT_ADD">
		<candidateContainers>
			<containerQId>caseStudy</containerQId>
		</candidateContainers>
		<lifecycle>
			<checkpoint>
				<executionTime type="NOW"/>
				<actions>
					<correlation execOrder="1"/>
					<email execOrder="2">
						<emailTemplate>
							<subject templateName="addContentOpp_subject.vm"/>
							<body templateName="addCasestudyOpp_body.vm"/>
						</emailTemplate>
						<emailContent>
							<triggerEntity/>
							<correlatedEntities>
								<entity>
									<contentTypes>
										<containerQId>customer.opportunity</containerQId>
									</contentTypes>
									<filterTags>
										<tag>OPP_VIA_SOL</tag>
									</filterTags>
								</entity>
							</correlatedEntities>			
						</emailContent>
						<recipient>
							<correlatedUsers>
								<users>
									<filterTags>
										<tag>OPP_SALES_REP</tag>
									</filterTags>
								</users>
							</correlatedUsers>
						</recipient>
					</email>
				</actions>
			</checkpoint>	
			<!--checkpoint>
				<executionTime type="LATER">
					<after timeUnit="MIN" timeValue="5"/>
				</executionTime>
				<actions>
					<correlation execOrder="1"/>
					<email execOrder="2">
						<emailTemplate>
							<subject templateName="salesTipOpp_subject.vm"/>
							<body templateName="salesTipOpp_body.vm"/>
						</emailTemplate>
						<emailContent>
							<triggerEntity/>
							<correlatedEntities>
								<entity>
									<contentTypes>
										<containerQId>customer.opportunity</containerQId>
										<containerQId>competitor</containerQId>										
									</contentTypes>
									<filterTags>
										<tag>OPP_VIA_SOL</tag>
										<tag>COMP_VIA_OPP</tag>										
									</filterTags>
								</entity>
							</correlatedEntities>			
						</emailContent>
						<recipient>
							<correlatedUsers>
								<users>
									<filterTags>
										<tag>OPP_SALES_REP</tag>
									</filterTags>
								</users>
							</correlatedUsers>
						</recipient>
					</email>
				</actions>
			</checkpoint-->							
		</lifecycle>
	</contentTriggerDef>
	<contentTriggerDef id="case-study-update-trigger" type="CONTENT_UPDATE">
		<candidateContainers>
			<containerQId>caseStudy</containerQId>
		</candidateContainers>
		<lifecycle>
			<checkpoint>
				<executionTime type="NOW"/>
				<actions>
					<correlation execOrder="1"/>
					<email execOrder="2">
						<emailTemplate>
							<subject templateName="addContentOpp_subject.vm"/>
							<body templateName="addCasestudyOpp_body.vm"/>
						</emailTemplate>
						<emailContent>
							<triggerEntity/>
							<correlatedEntities>
								<entity>
									<contentTypes>
										<containerQId>customer.opportunity</containerQId>
									</contentTypes>
									<filterTags>
										<tag>OPP_VIA_SOL</tag>
									</filterTags>
								</entity>
							</correlatedEntities>			
						</emailContent>
						<recipient>
							<correlatedUsers>
								<users>
									<filterTags>
										<tag>OPP_SALES_REP</tag>
									</filterTags>
								</users>
							</correlatedUsers>
						</recipient>
					</email>
				</actions>
			</checkpoint>	
		</lifecycle>
	</contentTriggerDef>	
</triggersDef>

=== u-learn/enablix/services/enablix-app/ext-resources/trigger/enablixmaster/add-update-salesplay-triggers.xml
<?xml version="1.0" encoding="utf-8"?>
<triggersDef xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/trigger-lifecycle.xsd">
	<contentTriggerDef id="add-salesplay-trigger" type="CONTENT_ADD">
		<candidateContainers>
			<containerQId>salesPlay</containerQId>
		</candidateContainers>
		<lifecycle>
			<checkpoint>
				<executionTime type="NOW"/>
				<actions>
					<correlation execOrder="1"/>
					<email execOrder="2">
						<emailTemplate>
							<subject templateName="addSalesplay_subject.vm"/>
							<body templateName="addSalesplay_body.vm"/>
						</emailTemplate>
						<emailContent>
							<triggerEntity/>
						</emailContent>
						<recipient>
							<correlatedUsers>
								<users>
									<filterTags>
										<tag>SALES_REPS</tag>
									</filterTags>
								</users>
							</correlatedUsers>
						</recipient>
					</email>
				</actions>
			</checkpoint>
			<checkpoint>
				<executionTime type="LATER">
					<after timeUnit="MIN" timeValue="3"/>
				</executionTime>
				<actions>
					<correlation execOrder="1"/>
					<email execOrder="2">
						<emailTemplate>
							<subject templateName="salesPlayProdSol_subject.vm"/>
							<body templateName="salesPlayProdSol_body.vm"/>
						</emailTemplate>
						<emailContent>
							<triggerEntity/>
							<correlatedEntities>
								<entity>
									<contentTypes>
										<containerQId>product</containerQId>
										<containerQId>solution</containerQId>										
									</contentTypes>
									<filterTags>
										<tag>LINKED_PROD</tag>
										<tag>LINKED_SOL</tag>										
									</filterTags>
								</entity>
							</correlatedEntities>			
						</emailContent>
						<recipient>
							<correlatedUsers>
								<users>
									<filterTags>
										<tag>SALES_REPS</tag>
									</filterTags>
								</users>
							</correlatedUsers>
						</recipient>
					</email>
				</actions>
			</checkpoint>	
			<checkpoint>
				<executionTime type="LATER">
					<after timeUnit="MIN" timeValue="6"/>
				</executionTime>
				<actions>
					<correlation execOrder="1"/>
					<email execOrder="2">
						<emailTemplate>
							<subject templateName="salesPlayComp_subject.vm"/>
							<body templateName="salesPlayComp_body.vm"/>
						</emailTemplate>
						<emailContent>
							<triggerEntity/>
							<correlatedEntities>
								<entity>
									<contentTypes>
										<containerQId>competitive</containerQId>
									</contentTypes>
									<filterTags>
										<tag>LINKED_COMP</tag>										
									</filterTags>
								</entity>
							</correlatedEntities>			
						</emailContent>
						<recipient>
							<correlatedUsers>
								<users>
									<filterTags>
										<tag>SALES_REPS</tag>
									</filterTags>
								</users>
							</correlatedUsers>
						</recipient>
					</email>
				</actions>
			</checkpoint>									
			<checkpoint>
				<executionTime type="LATER">
					<after timeUnit="MIN" timeValue="8"/>
				</executionTime>
				<actions>
					<correlation execOrder="1"/>
					<email execOrder="2">
						<emailTemplate>
							<subject templateName="introProd_subject.vm"/>
							<body templateName="introProd_body.vm"/>
						</emailTemplate>
						<emailContent>
							<triggerEntity/>
							<correlatedEntities>
								<entity>
									<contentTypes>
										<containerQId>product</containerQId>
										<containerQId>whitepaper</containerQId>
										<containerQId>salesDeck</containerQId>
										<containerQId>battlecard</containerQId>
										<containerQId>caseStudy</containerQId>																																								
									</contentTypes>
									<filterTags>
										<tag>INTRO_PROD</tag>	
										<tag>PROD_BATTLECARD</tag>	
										<tag>PROD_SALES_DECK</tag>	
										<tag>PROD_WP</tag>	
										<tag>PROD_CS</tag>																																																		
									</filterTags>
								</entity>
							</correlatedEntities>			
						</emailContent>
						<recipient>
							<correlatedUsers>
								<users>
									<filterTags>
										<tag>SALES_REPS</tag>
									</filterTags>
								</users>
							</correlatedUsers>
						</recipient>
					</email>
				</actions>
			</checkpoint>									
		</lifecycle>
	</contentTriggerDef>
</triggersDef>

=== u-learn/enablix/services/enablix-app/ext-resources/trigger/oraclefccm/add-update-triggers.xml
<?xml version="1.0" encoding="utf-8"?>
<triggersDef xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/trigger-lifecycle.xsd">
	<contentTriggerDef id="pipeline-report-add-trigger" type="CONTENT_ADD">
		<candidateContainers>
			<containerQId>content</containerQId>
		</candidateContainers>
		<lifecycle>
			<checkpoint>
				<executionTime type="NOW"/>
				<actions>
					<correlation execOrder="1"/>
					<email execOrder="2">
						<emailTemplate>
							<subject templateName="addPipelineReport_subject.vm"/>
							<body templateName="addPipelineReport_body.vm"/>
						</emailTemplate>
						<emailContent>
							<triggerEntity/>
						</emailContent>
						<recipient>
							<correlatedUsers>
								<users>
									<filterTags>
										<tag>ALL_USERS</tag>
									</filterTags>
								</users>
							</correlatedUsers>
						</recipient>
					</email>
				</actions>
			</checkpoint>	
		</lifecycle>
	</contentTriggerDef>
	<contentTriggerDef id="pipeline-report-update-trigger" type="CONTENT_UPDATE">
		<candidateContainers>
			<containerQId>content</containerQId>
		</candidateContainers>
		<lifecycle>
			<checkpoint>
				<executionTime type="NOW"/>
				<actions>
					<correlation execOrder="1"/>
					<email execOrder="2">
						<emailTemplate>
							<subject templateName="addPipelineReport_subject.vm"/>
							<body templateName="addPipelineReport_body.vm"/>
						</emailTemplate>
						<emailContent>
							<triggerEntity/>
						</emailContent>
						<recipient>
							<correlatedUsers>
								<users>
									<filterTags>
										<tag>ALL_USERS</tag>
									</filterTags>
								</users>
							</correlatedUsers>
						</recipient>
					</email>
				</actions>
			</checkpoint>	
		</lifecycle>
	</contentTriggerDef>
	<contentTriggerDef id="case-study-add-trigger" type="CONTENT_ADD">
		<candidateContainers>
			<containerQId>caseStudy</containerQId>
		</candidateContainers>
		<lifecycle>
			<checkpoint>
				<executionTime type="NOW"/>
				<actions>
					<correlation execOrder="1"/>
					<email execOrder="2">
						<emailTemplate>
							<subject templateName="addContent_subject.vm"/>
							<body templateName="addContent_body.vm"/>
						</emailTemplate>
						<emailContent>
							<triggerEntity/>
						</emailContent>
						<recipient>
							<correlatedUsers>
								<users>
									<filterTags>
										<tag>PRE_SALES_USER</tag>
									</filterTags>
								</users>
							</correlatedUsers>
						</recipient>
					</email>
				</actions>
			</checkpoint>	
		</lifecycle>
	</contentTriggerDef>
	<contentTriggerDef id="case-study-update-trigger" type="CONTENT_UPDATE">
		<candidateContainers>
			<containerQId>caseStudy</containerQId>
		</candidateContainers>
		<lifecycle>
			<checkpoint>
				<executionTime type="NOW"/>
				<actions>
					<correlation execOrder="1"/>
					<email execOrder="2">
						<emailTemplate>
							<subject templateName="addContent_subject.vm"/>
							<body templateName="addContent_body.vm"/>
						</emailTemplate>
						<emailContent>
							<triggerEntity/>
						</emailContent>
						<recipient>
							<correlatedUsers>
								<users>
									<filterTags>
										<tag>PRE_SALES_USER</tag>
									</filterTags>
								</users>
							</correlatedUsers>
						</recipient>
					</email>
				</actions>
			</checkpoint>	
		</lifecycle>
	</contentTriggerDef>	
</triggersDef>

=== u-learn/enablix/services/enablix-app/ext-resources/trigger/enablixmaster/add-update-triggers.xml
<?xml version="1.0" encoding="utf-8"?>
<triggersDef xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/trigger-lifecycle.xsd">
	<contentTriggerDef id="cust-opportunity-add-trigger" type="CONTENT_UPDATE">
		<candidateContainers>
			<containerQId>customer.opportunity</containerQId>
		</candidateContainers>
		<lifecycle>
			<checkpoint>
				<executionTime type="NOW"/>
				<actions>
					<correlation execOrder="1"/>
					<email execOrder="2">
						<emailTemplate>
							<subject templateName="addContent_subject.vm"/>
							<body templateName="addContent_body.vm"/>
						</emailTemplate>
						<emailContent>
							<correlatedEntities>
								<entity>
									<contentTypes>
										<containerQId>whitepaper</containerQId>
									</contentTypes>
									<filterTags>
										<tag>LINK_VIA_SOLN</tag>
									</filterTags>
								</entity>
							</correlatedEntities>
						</emailContent>
						<recipient>
							<allUsers/>
						</recipient>
					</email>
				</actions>
			</checkpoint>	
		</lifecycle>
	</contentTriggerDef>
</triggersDef>
